function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t456_setListMagin(recid,imglogo){if($(window).width()>980){var t456__menu=$('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t456__list_item a[href='"+url+"']").addClass("t-active");$(".t456__list_item a[href='"+url+"/']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if($(window).width()>=960){var t456_navLinks=$("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=$(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref($(this));if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=$(this)});$(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));$('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);setTimeout(function(){t456_updateSectionsOffsets(t456_sections);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},1000);t456_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t456_navLinks.removeClass('t-active');t456_sectionIdTonavigationLink[t456_getSectionByHref($(this)).attr("id")].addClass('t-active');t456_clickedSectionId=t456_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){$(sections).each(function(){var t456_curSection=$(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var t456_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t456_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t456_curLinkValue.substring(1)+"']")}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=$(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
$(t456_sections).each(function(e){var t456_curSection=$(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=$(document).height()-$(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t456_opened")});$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t602_init(recid){var t602_lastCall,t602_timeoutId,t602_interval=100;$(window).scroll(function(){var t602_now=new Date().getTime();if(t602_lastCall&&t602_now<(t602_lastCall+t602_interval)){clearTimeout(t602_timeoutId);t602_timeoutId=setTimeout(function(){t602_lastCall=t602_now;t602_setProgressBarWidth(recid)},t602_interval-(t602_now-t602_lastCall))}else{t602_lastCall=t602_now;t602_setProgressBarWidth(recid)}})}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=$(window).scrollTop(),t602_docHeight=$(document).height(),t602_winHeight=$(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;$(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t774_init(recid){t774_unifyHeights(recid);$(window).bind('resize',t_throttle(function(){t774_unifyHeights(recid)},200));$(".t774").bind("displayChanged",function(){t774_unifyHeights(recid)});$(window).load(function(){t774_unifyHeights(recid)})}
function t774_unifyHeights(recid){var t774_el=$('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if($(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if($(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}
else{if($(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=$(this).find(".t774__textwrapper"),t774_curBtns=$(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t842_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t842');var doResize;t842_unifyHeights(rec);$(window).resize(function(){clearTimeout(doResize);doResize=setTimeout(function(){t842_unifyHeights(rec)},200)});$(window).load(function(){t842_unifyHeights(rec)});$('.t842').bind('displayChanged',function(){t842_unifyHeights(rec)});if(container.hasClass('t842__previewmode')){setInterval(function(){t842_unifyHeights(rec)},5000)}}
function t842_unifyHeights(rec){if($(window).width()>=960){rec.find('.t842 .t-container .t842__row').each(function(){var highestBox=0;var row=$(this);$('.t842__inner-col',this).each(function(){var col=$(this);var wrap=col.find('.t842__wrap');var colHeight=wrap.outerHeight();if(colHeight>highestBox){highestBox=colHeight}});$('.t842__inner-col',this).css('height',highestBox);$('.t842__bgimg',this).css('height',highestBox)})}else{$('.t842__inner-col').css('height','auto');$('.t842__bgimg').css('height','auto')}}